### ISSUE TITLE
This isn't an issue but a recommendation

### ISSUE THREAD

**Issue by SmplyVortexian** [etcherfx/precisionclient#2]
Can You Add Nebula 32x Texture Pack? I Would Appreciate It. 
![2022-07-11_17 46 58](https://user-images.githubusercontent.com/110855363/183506435-3d02d91a-fcc3-4e05-be9f-4cf6be95aa6e.png)

**Comment by etcherfx** [comment]
We are working on bombies 180k, Walibear 1 million, and Nebula 32x right now.

**Comment by SmplyVortexian** [comment]
thank you. do you have any fixed date that it will be finished on or by?

**Comment by etcherfx** [comment]
It will be finished by 8/14/22

**Comment by SmplyVortexian** [comment]
okay thank you

**Comment by SmplyVortexian** [comment]
Nebula is just my favorite pack so i just needed to know 😀
