### ISSUE TITLE
Precision Client New Mods!

### ISSUE THREAD

**Issue by ZGStuff** [etcherfx/precisionclient#5]
so um i have some stuff for new mods like a minimap (was supposed to be in Trident Client but cancelled) or like idk speedbridge (enabled on bedwars ONLY). Please consider these. also NEW TEXTURES coming from me for the SMP im making, Infinite SMP.

**Comment by ZGStuff** [comment]
these are the textures (they're for 1.19 lol
[InfiniPack (1).zip](https://github.com/etcherfx/precisionclient/files/9364935/InfiniPack.1.zip)
)

**Comment by ZGStuff** [comment]
also Singleplayer from EaglercraftBeta

**Comment by etcherfx** [comment]
no why would i add textures specifically for your server and what is "speedbridge (enabled on bedwars ONLY)"?

**Comment by SmplyVortexian** [comment]
Lmao it isn't ur client zgstufd

**Comment by SmplyVortexian** [comment]
The clients are not competing

**Comment by SmplyVortexian** [comment]
I think that is like a hack idk

**Comment by SmplyVortexian** [comment]
The speedbridge thing

**Comment by SmplyVortexian** [comment]
One recommendation I have is motion blur

**Comment by ZGStuff** [comment]
ok ok i messed up but the Infinite SMP textures just make it look cool with armor looking like its made of the Infinity Stones (marvel)

**Comment by ZGStuff** [comment]
im closing bc its not getting done
:)
