### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 3kh0** [etcherfx/precisionclient#6]
I have the source code, and I want to add a few default servers to the menu, when decoding minecraftOpts[texture] with base64, i get this

![image](https://user-images.githubusercontent.com/58097612/187314357-163f224a-5f19-41fb-9296-a22b242ec87f.png)

any help?

**Comment by etcherfx** [comment]
download server_template.dat from the official eaglercraft repo and use an nbt editor to edit the file (add servers).

**Comment by 3kh0** [comment]
Sorry, I can not seem to find this file, `server_template`

![image](https://user-images.githubusercontent.com/58097612/187528889-c8902ae2-0fce-4cc5-8404-9cf659185ea7.png)

**Comment by meow-studios** [comment]
use this: https://shhnowisnottheti.me/ayunEaglerConfig/

**Comment by etcherfx** [comment]
> use this: https://shhnowisnottheti.me/ayunEaglerConfig/

Yeah use this @3kh0

**Comment by 3kh0** [comment]
Thanks so much @meow-studios!
