### ISSUE TITLE
capes not working

### ISSUE THREAD

**Issue by CuriousCoder1232** [etcherfx/precisionclient#7]
i have downloaded capes off minecraftcapes.net adn they dont dissapear `<!DOCTYPE html>
<html>
   <head>
      <title>e</title>
   </head>

   <body>
      <h1>Company</h1>
      <p>
         <a href="https://youareanidiot.org/">team</a>  
         hard to provide free learning content.
      </p>
   </body>
</html>`

**Comment by CuriousCoder1232** [comment]
sorry about that and stuff umm yeah

**Comment by ninefivenine** [comment]
What is "adn they don't dissapear `" Supposed to mean?

And you probably can't use the capes you downloaded from minecraftcapes.net because you are trying to use a animated cape or you are using a high resolution cape.

**Comment by CuriousCoder1232** [comment]
Can you send me some capes that work and im using simple ones like not animated

**Comment by CuriousCoder1232** [comment]
Adn was and

**Comment by CuriousCoder1232** [comment]
I dont want the letters OF l like something custom

**Comment by ninefivenine** [comment]
Then that isn't a precision client issue
